using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Runtime.InteropServices;

namespace RackMaster.SEQ.TCP
{
    public class TcpDataDef
    {
        // CIM -> RM BIT
        public enum ReceiveBitMap
        {
            MST_Emo_Request = 0,
            RM_Servo_On_Request,
            
            RM_Servo_Off_Request = 3,

            RM_Auto_Request = 5,

            RM_Auto_Stop_Request = 7,

            RM_Error_Reset_Request = 9,
            MST_Soft_Error_State,

            RM_Time_Sync = 16,

            RM_Auto_Teaching_Start_Request = 21,
            RM_Auto_Teaching_Complete_ACK,
            RM_Auto_Teaching_Complete_Alarm_ACK,
            RM_Auto_Teaching_Stop_Request,

            RM_From_Start_Request = 32,
            RM_From_Complete_ACK,
            RM_To_Start_Request,
            RM_To_Complete_ACK,

            RM_Maint_Start_Request = 38,
            RM_Maint_Complete_ACK,

            RM_Store_Alt_ACK = 43,
            RM_Source_Empty_ACK,
            RM_Double_Storage_ACK,
            RM_Resume_Request_ACK,

            RM_Teaching_Read_Write_Start = 48,

            RM_HP_Door_Open = 64,
            RM_OP_Door_Open,
            RM_HP_EMO,
            RM_OP_EMO,
            RM_HP_Escape,
            RM_OP_Escape,
            RM_Key_Auto,

            RM_X_Axis_Max_OverLoad_Reset = 102,
            RM_Z_Axis_Max_OverLoad_Reset,
            RM_A_Axis_Max_OverLoad_Reset,
            RM_T_Axis_Max_OverLoad_Reset,

            RM_X_Axis_Max_OverLoad_Apply = 107,
            RM_Z_Axis_Max_OverLoad_Apply,
            RM_A_Axis_Max_OverLoad_Apply,
            RM_T_Axis_Max_OverLoad_Apply,

            RM_X_Axis_Auto_Home_Cur_Reset = 118,
            RM_Z_Axis_Auto_Home_Cur_Reset,
            RM_A_Axis_Auto_Home_Cur_Reset,
            RM_T_Axis_Auto_Home_Cur_Reset,

            RM_X_Axis_Auto_Home_Count_Apply = 123,
            RM_Z_Axis_Auto_Home_Count_Apply,
            RM_A_Axis_Auto_Home_Count_Apply,
            RM_T_Axis_Auto_Home_Count_Apply,

            PIO_Load_Request = 208,
            PIO_Unload_Request,
            PIO_Ready,
            PIO_Port_Error,

            MAX_COUNT,
        }

        // RM -> CIM BIT
        public enum SendBitMap
        {
            Servo_On_Ready = 0,
            Servo_On_State,
            Servo_Off_Ready,
            Servo_Off_State,
            Auto_Ready,
            Auto_State,
            Manual_Ready,
            Manual_State,

            Error_State = 9,
            Home_State,

            Fan1_On_State = 14,
            Fan2_On_State,

            Auto_Teaching_State = 20,
            Auto_Teaching_Start_ACK,
            Auto_Teaching_Complete,
            Auto_Teaching_Alarm,

            From_Start_ACK = 32,
            From_Complete,
            To_Start_ACK,
            To_Complete,

            Maint_Move_Start_ACK = 38,
            Maint_Move_Complete,

            Store_Alt_Request = 43,
            Source_Empty_Request,
            Double_Storage_Request,
            Resume_Request_Request,

            Teaching_RW_Ready = 48,
            Teaching_Read_Complete,

            Accessing_RM_Down_From = 51,
            Accessing_RM_Dwon_To,

            From_Ready = 58,
            To_Ready,
            Idle_State,
            Active_State,

            XZT_Going_State = 64,

            Maint_Move_State = 67,
            From_State,
            To_State,

            X_Axis_FWD_State = 72,
            X_Axis_BWD_State,
            X_Axis_Max_Speed_State,
            Arm_Home_Position_State,
            Turn_Left_Position_State,
            Turn_Right_Position_State,
            CST_Empty,
            CST_ON,

            X_Axis_Power_On,
            X_Axis_Servo_On,
            X_Axis_HomeDone,
            Z_Axis_Power_On,
            Z_Axis_Servo_On,
            Z_Axis_HomeDone,
            A_Axis_Power_On,
            A_Axis_Servo_On,
            A_Axis_HomeDone,
            T_Axis_Power_On,
            T_Axis_Servo_On,
            T_Axis_HomeDone,

            EMO_On = 99,
            GOT_EMO_On,
            Double_Storage_Sensor,
            Arm_CST_All_Undetected,
            Arm_CST_1_Detected_Sensor,
            Arm_CST_2_Detected_Sensor,
            Arm_CST_Diagonal_Detected_Sensor,
            Left_From_Sensor,
            Left_To_Sensor,
            Right_From_Sensor,
            Right_To_Sensor,
            Left_1_Projecting_Sensor_Front,
            Left_2_Projecting_Sensor_Rear,
            Right_1_Projecting_Sensor_Front,
            Right_2_Projecting_Sensor_Rear,
            Z_Axis_HP_Home_Sensor,
            Z_Axis_HP_NOT_Sensor,
            Z_Axis_HP_POT_Sensor,

            HP_EMO_Push = 120,
            OP_EMO_Push,

            GOT_Detect = 128,
            Position_Sensor_1,
            Position_Sensor_2,
            X_Axis_HP_Home_Sensor,
            X_Axis_HP_Slow_Sensor,
            X_Axis_HP_NOT_Sensor,
            X_Axis_OP_Slow_Sensor,
            X_Axis_OP_POT_Sensor,
            A_Axis_Home_Sensor,
            A_Axis_NOT_Sensor,
            A_Axis_POT_Sensor,
            A_Axis_POS_1_Sensor,
            A_Axis_POS_2_Sensor,
            A_Axis_POS_3_Sensor,
            T_Axis_Home_Sensor,
            T_Axis_NOT_Sensor,
            T_Axis_POT_Sensor,
            T_Axis_POS_Sensor,

            CPS_Second_Run = 154,
            CPS_Second_Fault,

            From_Step_0_Complete = 160,
            From_Step_1_Complete,
            From_Step_2_Complete,
            From_Step_3_Complete,
            From_Step_4_Complete,
            To_Step_0_Complete,
            To_Step_1_Complete,
            To_Step_2_Complete,
            To_Step_3_Complete,
            To_Step_4_Complete,

            Communication_Check = 171,
            X_Axis_Busy,
            Z_Axis_Busy,
            T_Axis_Busy,
            A_Axis_Busy,

            PIO_TR_Request = 208,
            PIO_Busy,
            PIO_Complete,
            PIO_STK_Error,

            MAX_COUNT,
        }

        // CIM -> RM WORD
        public enum ReceiveWordMap
        {
            CST_ID_PIO_Word_0,
            CST_ID_PIO_Word_1,
            CST_ID_PIO_Word_2,
            CST_ID_PIO_Word_3,
            CST_ID_PIO_Word_4,
            CST_ID_PIO_Word_5,
            CST_ID_PIO_Word_6,
            CST_ID_PIO_Word_7,
            CST_ID_PIO_Word_8,
            CST_ID_PIO_Word_9,
            CST_ID_PIO_Word_10,
            CST_ID_PIO_Word_11,
            CST_ID_PIO_Word_12,
            CST_ID_PIO_Word_13,
            CST_ID_PIO_Word_14,
            CST_ID_PIO_Word_15,
            CST_ID_PIO_Word_16,
            CST_ID_PIO_Word_17,
            CST_ID_PIO_Word_18,
            CST_ID_PIO_Word_19,
            CST_ID_PIO_Word_20,
            CST_ID_PIO_Word_21,
            CST_ID_PIO_Word_22,
            CST_ID_PIO_Word_23,
            CST_ID_PIO_Word_24,
            CST_ID_PIO_Word_25,
            CST_ID_PIO_Word_26,
            CST_ID_PIO_Word_27,
            CST_ID_PIO_Word_28,
            CST_ID_PIO_Word_29,
            CST_ID_PIO_Word_30,
            CST_ID_PIO_Word_31,
            CST_ID_PIO_Word_32,
            CST_ID_PIO_Word_33,
            CST_ID_PIO_Word_34,
            CST_ID_PIO_Word_35,
            CST_ID_PIO_Word_36,
            CST_ID_PIO_Word_37,
            CST_ID_PIO_Word_38,
            CST_ID_PIO_Word_39,
            CST_ID_PIO_Word_40,
            CST_ID_PIO_Word_41,
            CST_ID_PIO_Word_42,
            CST_ID_PIO_Word_43,
            CST_ID_PIO_Word_44,
            CST_ID_PIO_Word_45,
            CST_ID_PIO_Word_46,
            CST_ID_PIO_Word_47,
            CST_ID_PIO_Word_48,
            CST_ID_PIO_Word_49,
            CST_ID_PIO_Word_50,
            CST_ID_PIO_Word_51,
            CST_ID_PIO_Word_52,
            CST_ID_PIO_Word_53,
            CST_ID_PIO_Word_54,
            CST_ID_PIO_Word_55,
            CST_ID_PIO_Word_56,
            CST_ID_PIO_Word_57,
            CST_ID_PIO_Word_58,
            CST_ID_PIO_Word_59,
            CST_ID_PIO_Word_60,
            CST_ID_PIO_Word_61,
            CST_ID_PIO_Word_62,
            CST_ID_PIO_Word_63,

            Year,
            Month,
            Day,
            Hour,
            Minute,
            Second,
            Day_Of_The_Week,

            RM_FROM_SHELF_ID_0 = 80,
            RM_FROM_SHELF_ID_1,
            RM_TO_SHELF_ID_0,
            RM_TO_SHELF_ID_1,

            Teaching_RW_ID_0 = 90,
            Teaching_RW_ID_1,
            Auto_Teaching_ID_0,
            Auto_Teaching_ID_1,
            Auto_Teaching_X_Axis_Data,
            Auto_Teaching_Z_Axis_Data,

            RM_Speed_X_Axis_Percent = 108,
            RM_Speed_Z_Axis_Percent,
            RM_Speed_A_Axis_Percent,
            RM_Speed_T_Axis_Percent,

            X_Axis_Max_OverLoad_Limit = 113,
            Z_Axis_Max_OverLoad_Limit,
            A_Axis_Max_OverLoad_Limit,
            T_Axis_Max_OverLoad_Limit,

            Watchdog_Word_Data = 164,

            MAX_COUNT,
        }

        // RM -> CIM WORD
        public enum SendWordMap
        {
            CST_ID_PIO_Word_0,
            CST_ID_PIO_Word_1,
            CST_ID_PIO_Word_2,
            CST_ID_PIO_Word_3,
            CST_ID_PIO_Word_4,
            CST_ID_PIO_Word_5,
            CST_ID_PIO_Word_6,
            CST_ID_PIO_Word_7,
            CST_ID_PIO_Word_8,
            CST_ID_PIO_Word_9,
            CST_ID_PIO_Word_10,
            CST_ID_PIO_Word_11,
            CST_ID_PIO_Word_12,
            CST_ID_PIO_Word_13,
            CST_ID_PIO_Word_14,
            CST_ID_PIO_Word_15,
            CST_ID_PIO_Word_16,
            CST_ID_PIO_Word_17,
            CST_ID_PIO_Word_18,
            CST_ID_PIO_Word_19,
            CST_ID_PIO_Word_20,
            CST_ID_PIO_Word_21,
            CST_ID_PIO_Word_22,
            CST_ID_PIO_Word_23,
            CST_ID_PIO_Word_24,
            CST_ID_PIO_Word_25,
            CST_ID_PIO_Word_26,
            CST_ID_PIO_Word_27,
            CST_ID_PIO_Word_28,
            CST_ID_PIO_Word_29,
            CST_ID_PIO_Word_30,
            CST_ID_PIO_Word_31,
            CST_ID_PIO_Word_32,
            CST_ID_PIO_Word_33,
            CST_ID_PIO_Word_34,
            CST_ID_PIO_Word_35,
            CST_ID_PIO_Word_36,
            CST_ID_PIO_Word_37,
            CST_ID_PIO_Word_38,
            CST_ID_PIO_Word_39,
            CST_ID_PIO_Word_40,
            CST_ID_PIO_Word_41,
            CST_ID_PIO_Word_42,
            CST_ID_PIO_Word_43,
            CST_ID_PIO_Word_44,
            CST_ID_PIO_Word_45,
            CST_ID_PIO_Word_46,
            CST_ID_PIO_Word_47,
            CST_ID_PIO_Word_48,
            CST_ID_PIO_Word_49,
            CST_ID_PIO_Word_50,
            CST_ID_PIO_Word_51,
            CST_ID_PIO_Word_52,
            CST_ID_PIO_Word_53,
            CST_ID_PIO_Word_54,
            CST_ID_PIO_Word_55,
            CST_ID_PIO_Word_56,
            CST_ID_PIO_Word_57,
            CST_ID_PIO_Word_58,
            CST_ID_PIO_Word_59,
            CST_ID_PIO_Word_60,
            CST_ID_PIO_Word_61,
            CST_ID_PIO_Word_62,
            CST_ID_PIO_Word_63,

            X_Axis_Cur_Position_0,
            X_Axis_Cur_Position_1,
            X_Axis_Target_Position_0,
            X_Axis_Target_Position_1,
            X_Axis_Cur_Velocity_0,
            X_Axis_Cur_Velocity_1,
            X_Axis_Cur_Max_OverLoad,
            X_Axis_Setting_Max_OverLoad,

            X_Axis_ACC = 74,
            X_Axis_DEC,
            X_Axis_Cur_Torque,

            Z_Axis_Cur_Position_0 = 80,
            Z_Axis_Cur_Position_1,
            Z_Axis_Target_Position_0,
            Z_Axis_Target_Position_1,
            Z_Axis_Cur_Velocity_0,
            Z_Axis_Cur_Velocity_1,
            Z_Axis_Cur_Max_OverLoad,
            Z_Axis_Setting_Max_OverLoad,

            Z_Axis_ACC = 90,
            Z_Axis_DEC,
            Z_Axis_Cur_Torque,

            A_Axis_Cur_Position_0 = 96,
            A_Axis_Cur_Position_1,
            A_Axis_Target_Position_0,
            A_Axis_Target_Position_1,
            A_Axis_Cur_Velocity_0,
            A_Axis_Cur_Velocity_1,
            A_Axis_Cur_Max_OverLoad,
            A_Axis_Setting_Max_OverLoad,

            A_Axis_ACC = 106,
            A_Axis_DEC,
            A_Axis_Cur_Torque,

            T_Axis_Cur_Position_0 = 112,
            T_Axis_Cur_Position_1,
            T_Axis_Target_Position_0,
            T_Axis_Target_Position_1,
            T_Axis_Cur_Velocity_0,
            T_Axis_Cur_Velocity_1,
            T_Axis_Cur_Max_OverLoad,
            T_Axis_Setting_Max_OverLoad,

            T_Axis_ACC = 122,
            T_Axis_DEC,
            T_Axis_Cur_Torque,

            Auto_Speed_Percent_X = 128,
            Auto_Speed_Percent_Z,
            Auto_Speed_Percent_A,
            Auto_Speed_Percent_T,
            Auto_Teaching_Id_0,
            Auto_Teaching_Id_1,
            Auto_Teaching_Target_X,
            Auto_Teaching_Target_Z,

            Error_Word_0 = 144,
            Error_Word_1,
            Error_Word_2,
            Error_Word_3,
            Error_Word_4,
            Error_Word_5,
            Error_Word_6,
            Error_Word_7,
            Error_Word_8,
            Error_Word_9,
            Error_Word_10,
            Error_Word_11,
            Error_Word_12,

            Teaching_X_Axis_Data_0 = 162,
            Teaching_X_Axis_Data_1,
            Teaching_Z_Axis_Data_0,
            Teaching_Z_Axis_Data_1,
            Teaching_A_Axis_Data_0,
            Teaching_A_Axis_Data_1,
            Teaching_T_Axis_Data_0,
            Teaching_T_Axis_Data_1,

            FROM_SHELF_ID_0 = 172,
            FROM_SHELF_ID_1,
            TO_SHELF_ID_0,
            TO_SHELF_ID_1,

            X_Axis_Avr_Torque,
            X_Axis_Peak_Torque,
            Z_Axis_Avr_Torque,
            Z_Axis_Peak_Torque,
            A_Axis_Avr_Torque,
            A_Axis_Peak_Torque,
            T_Axis_Avr_Torque,
            T_Axis_Peak_Torque,

            Watchdog_Word_Data = 186,
            X_Axis_Cur_Limit_Torque,
            Z_Axis_Cur_Limit_Torque,
            A_Axis_Cur_Limit_Torque,
            T_Axis_Cur_Limit_Torque,

            RM_Auto_Step_Number = 192,

            Access_Shelf_ID_0 = 194,
            Access_Shelf_ID_1,
            X_Axis_Cumulative_Distance_0,
            X_Axis_Cumulative_Distance_1,
            Z_Axis_Cumulative_Distance_0,
            Z_Axis_Cumulative_Distance_1,
            A_Axis_Cumulative_Distance_0,
            A_Axis_Cumulative_Distance_1,
            T_Axis_Cumulative_Distance_0,
            T_Axis_Cumulative_Distance_1,

            MAX_COUNT,
        }
    }
}
